import type { Metadata } from "next";

import "./globals.css";
import NavBar from '@/app/components/NavBar'
import { Nunito } from "next/font/google";
import Footer from "./components/Footer";

export const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-full ${nunito.className}`}
      >
        
        <NavBar/>
        <main className="fade-in">
        {children}

        </main>
        <Footer/>
      </body>
    </html>
  );
}
